### ISSUE TITLE
RDF error on FedoraObject

### ISSUE THREAD

**Issue by laritakr** [ndlib/hesburgh_metrics#37]
Rake aborted with following:

NoMethodError: private method `readline' called for nil:NilClass
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/rdf-1.1.17.1/lib/rdf/reader.rb:496:in `readline'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/rdf-1.1.17.1/lib/rdf/ntriples/reader.rb:204:in `block in read_triple'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/rdf-1.1.17.1/lib/rdf/ntriples/reader.rb:203:in `loop'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/rdf-1.1.17.1/lib/rdf/ntriples/reader.rb:203:in `read_triple'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/rdf-1.1.17.1/lib/rdf/reader.rb:388:in `read_statement'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/rdf-1.1.17.1/lib/rdf/reader.rb:305:in `block in each_statement'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/rdf-1.1.17.1/lib/rdf/reader.rb:305:in `loop'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/rdf-1.1.17.1/lib/rdf/reader.rb:305:in `each_statement'
/home/app/metrics/releases/20160527162813/app/services/fedora_object_harvester.rb:138:in `block in parse_triples'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/rdf-1.1.17.1/lib/rdf/reader.rb:208:in `call'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/rdf-1.1.17.1/lib/rdf/reader.rb:208:in `initialize'
/home/app/metrics/releases/20160527162813/app/services/fedora_object_harvester.rb:137:in `new'
/home/app/metrics/releases/20160527162813/app/services/fedora_object_harvester.rb:137:in `parse_triples'
/home/app/metrics/releases/20160527162813/app/services/fedora_object_harvester.rb:50:in `get_resource_type'
/home/app/metrics/releases/20160527162813/app/services/fedora_object_harvester.rb:26:in `block in harvest'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/rubydora-1.7.5/lib/rubydora/repository.rb:73:in `call'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/rubydora-1.7.5/lib/rubydora/repository.rb:73:in `block in search'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
/home/app/metrics/shared/bundle/ruby/2.0.0/gems/rubydora-1.7.5/lib/rubydora/repository.rb:67:in `search'
/home/app/metrics/releases/20160527162813/app/services/fedora_object_harvester.rb:20:in `harvest'
/home/app/metrics/releases/20160527162813/lib/tasks/metrics.rake:22:in `block (2 levels) in <top (required)>'
/opt/ruby/current/bin/bundle:22:in `load'
/opt/ruby/current/bin/bundle:22:in `<main>'
Tasks: TOP => metrics:harvest_fedora

**Comment by laritakr** [comment]
Parse Triples is being called with nothing, which implies that the object had no descMetadata datastream. So I added defaults for each of the methods which access a datastream (those that didn't have them previously) in case that datastream doesn't exist.

We may want to consider logging the pid in error and skipping to the next @repo item, but for now this should be adequate.
